// src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { regexToAST, astToEpsilonNFA, epsilonNFAtoNFA, nfaToDFA } from './math'
import type { Graph } from './math/graph'
import FiniteAutomata from './components/FiniteAutomata.vue'
import RegexInfo from './components/RegexInfo.vue'
import AutomataInfo from './components/AutomataInfo.vue'

const regex = ref('')
const text = ref('')
const epsilonNFA = ref<Graph>()
const nfa = ref<Graph>()
const dfa = ref<Graph>()
const submit = () => {
  regex.value = '($' + text.value + ')'
  const ast = regexToAST(regex.value)
  epsilonNFA.value = astToEpsilonNFA(ast)
  nfa.value = epsilonNFAtoNFA(epsilonNFA.value)
  dfa.value = nfaToDFA(nfa.value)
}
</script>

<template>
  <main class="flex flex-col items-center h-screen p-4 gap-4 overflow-auto">
    <div class="flex flex-row flex-wrap gap-4">
      <RegexInfo />
      <AutomataInfo />
    </div>
    <form class="flex items-center gap-2 justify-center" v-on:submit.prevent="submit">
      <input
        name="regex"
        class="border-black p-2"
        v-model="text"
        placeholder="Enter your regex here"
      />
      <button class="hover:cursor-pointer" type="submit">Submit</button>
    </form>
    <FiniteAutomata v-if="epsilonNFA" :automata="epsilonNFA" title="Epsilon NFA" />
    <FiniteAutomata v-if="nfa" :automata="nfa" title="NFA" />
    <FiniteAutomata v-if="dfa" :automata="dfa" title="DFA" />
  </main>
</template>

<style scoped></style>

// src/app/page.tsx
"use client";
import { useState } from "react";
import { Button } from "~/components/ui/button";
import DFA from "~/components/ui/DFA";
import { Input } from "~/components/ui/input";

export default function HomePage() {
  const [regex, setRegex] = useState("");
  const [regexToConvert, setRegexToConvert] = useState("a");

  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-4 text-black">
      <div className="flex flex-col gap-2">
        <h1>Regex here</h1>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            setRegexToConvert(regex);
          }}
        >
          <Input
            value={regex}
            onChange={(e) => setRegex(e.target.value)}
            type="text"
            placeholder="Enter a regex"
          />
          <Button type="submit">Submit</Button>
        </form>
      </div>
      <div className="flex h-full min-h-96 flex-col gap-2">
        <h1>DFA here</h1>
        <DFA regex={regexToConvert} />
      </div>
    </main>
  );
}
